filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

- type: log
  paths:
    - '/app/logs/*.log'
  fields:
    logtype: application
  fields_under_root: true

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  index: "quickqueue-logs-%{+yyyy.MM.dd}"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  _source.enabled: false